### ISSUE TITLE
Error due to missing '-trimmed'

### ISSUE THREAD

**Issue by musicmichaelc** [leahvelleman/jekyll-lilypond#13]
# Error due to missing '-trimmed' in .svg file

I installed `jekyll-lilypond` and tried inserting some sample lilypond code into a markdown file (post), however after running `bundle exec jekyll serve`, I got the following error:

```
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/static_file.rb:71:in `stat': No such file or directory @ rb_file_s_stat - /Users/michael/sites/music-template/lilypond_files/fcf5de3d1b7e3729f701ea41da6b1b71-trimmed.svg (Errno::ENOENT)
```

It turned out that the `lilypond_files` directory included a file called `fcf5de3d1b7e3729f701ea41da6b1b71.svg`, but without the `'-trimmed'`.

## Temporary solution/workaround:

After running `rename -s '.svg' '-trimmed.svg' *.svg` in the `lilypond_files` directory, everything worked and I could see the rendered music on the page in the browser.  

However, Jekyll still gave me the following warning (I'm not quite sure why):

```
Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/michael/sites/music-template/_site/lilypond_files/fcf5de3d1b7e3729f701ea41da6b1b71-trimmed.svg
                     - /Users/michael/sites/music-template/lilypond_files/fcf5de3d1b7e3729f701ea41da6b1b71-trimmed.svg
                     - /Users/michael/sites/music-template/lilypond_files/fcf5de3d1b7e3729f701ea41da6b1b71-trimmed.svg
```

**Comment by leahvelleman** [comment]
Thanks for reporting this! Embarrassingly, it looks like I have an error in the installation instructions. The program that the plugin depends on for trimming image files is not ImageMagick, as the instructions state, but Inkscape. Can you try [installing Inkscape](https://inkscape.org/release/inkscape-1.0.2/) and see if that resolves the problem? Sorry for the confusion.

**Comment by musicmichaelc** [comment]
No problem&mdash;and yes, this resolved the problem easily&mdash;thanks!
